### ISSUE TITLE
default year still 2017

### ISSUE THREAD

**Issue by ilhamsuaib** [lutvie72/RackMonthPicker#11]
default year still not based on current year on the popup picker

**Comment by kal72** [comment]
I'm sorry I can not take updates, because I'm busy.

**Comment by suchoX** [comment]
The issue is fixed but is not on maven. Download the library as zip and add it as a local dependency.

**Comment by suchoX** [comment]
It has a GPL license. Can you make it Apache or MIT so that we can use it?

**Comment by kal72** [comment]
@suchoX Oke

**Comment by suchoX** [comment]
Thank you @lutvie72  Really appreciate it!
