### ISSUE TITLE
Not work proper with androidX

### ISSUE THREAD

**Issue by kaushikbhut** [lutvie72/RackMonthPicker#13]
![device-2019-09-21-142014](https://user-images.githubusercontent.com/52907987/65370917-bc50a280-dc7b-11e9-8bba-00251f968fe3.png)

**Comment by kal72** [comment]
thanks you

**Comment by kaushikbhut** [comment]
Please asap give me the solution.

**Comment by yudistirosaputro** [comment]
Thank for your feedback
we will migrate to AndroidX ASAP
