### ISSUE TITLE
Background of positive and negative buttons

### ISSUE THREAD

**Issue by Coder481** [lutvie72/RackMonthPicker#17]
The background of positive and negative buttons are same as their text color due to which their texts are not visible

**Comment by threeyulianto333** [comment]
[photo](https://lh3.googleusercontent.com/i2i0DKSMChe84HWaz_u4GX3yefc0i1_SJ5HCq57xn6WlY6NV1nizTlq6ePh9ZSyLvB_7tNpINIUo04mWOFmclfOV_jvtkDA4yni9w6cqEDST2_LELqhkDQb_ShAXd-yXFoBupFpUVDPk31WCM-mcsD2t2I-2E32RWWzmN3L0DPJyEw-JgatLs_iabTh1tIx9AMfuaGr3AanCfweokdxc8oEkTFl7QW5iS7kJ8hdMY-px-SYKwAUnE1F-JD0PMQ5nEW787wHuoxeUOPvPqNjAAInXxxnB0H1Y6Os9_EPeZS2wTcufoP1dusjaN3mOQ2Sqkh8NWS5FNfAc6HKpCjTGurh6fuIDvliGn_PSdSpDR4pJFaoy3_JM8WjWpmn6LqDaVcHTEjIbVNN9-7awJKVfMrFYoP7flu6Mxf6gumhUPE4r0eq5LCQfvanfhl4WItv20R6TNTBc8Rt_zCX3z1gWrWCytK7ryW8mlkltQE5n3LLXNBUEhpMEHMNfmrV_KxyBdfIUBQXGxc8BujfTGRBVy2UJzr0b0h1dhk7cpO0uPhCDEe4F6TUTswSgL_fNHX2mhcIxOpf6BBwZbzJ3I9_jIOkF44sAyRYfleAp-G9Qb6-JzvU56tAnVEcBvOMk3vDCkATzj4fIIyBtDKDaadQksUK4-vZq5uXxlLMe_JcirFFVB6llYiiwjRnk0793e9RfueioDT2lG0CsfJ_ElarPWFVI=w401-h867-no?authuser=1)


> The background of positive and negative buttons are same as their text color due to which their texts are not visible

i have some problem here

**Comment by ARNAB2203** [comment]
Same issue i am facing. Need option for text color.

**Comment by m-khanz** [comment]
By changing color theme, you can change the text-color, but the problem is theme color and text color will be same.

**Comment by MohamedRifay5** [comment]
i also have a same problem
