### ISSUE TITLE
Set Custom Month while creating/showing the Dialog

### ISSUE THREAD

**Issue by Shajeel-Afzal** [lutvie72/RackMonthPicker#5]
Is there any way to set custom month while creating the month picker dialog? Currently, it shows January as the selected month everytime we show the dialog, there should be the option to set custom month to show as the selected month in the dialog. 

Any plan to add that feature?

**Comment by Shadow1356** [comment]
@Shajeel-Afzal I was thinking the same thing and was planning on tackling the problem myself and seeing if I could come up with a pull request in the next couple of days.

**Comment by kal72** [comment]
@Shajeel-Afzal yes, but I still have busy, so can't fix immediately.
@Shadow1356 thanks.
