### ISSUE TITLE
setSelectedYear() is a Critical Update needed.

### ISSUE THREAD

**Issue by habeebrahmanomr** [lutvie72/RackMonthPicker#9]
Sir,
@lutvie72 
When the picker opened in january, 2018 its showing 2017 as year. 
When we click next button it is changed to 2019 and then clicked previous it came to 2018. So the update is very important. We are waiting for the update.

**Comment by kal72** [comment]
@habeeb1303 oke,okay, please wait.

**Comment by habeebrahmanomr** [comment]
When will u fix?

**Comment by ghost** [comment]
Yes. Its a funny mistake! But thanks ! Your library helps me ! :D I will be waiting for the update! :D

**Comment by fritz-playmaker** [comment]
Really need the update here. Would be waiting.

**Comment by arhn17** [comment]
yeah need the update please

**Comment by fritz-playmaker** [comment]
Update required here

**Comment by arhn17** [comment]
where is update this year in my program? @fritz-playmaker

**Comment by fritz-playmaker** [comment]
Downloaded the library-project as a zip file and imported it as a module with Android Studio, then I made the necessary changes to the library. The issue is that he assigns the variable year to 2017.  So I just removed that code and it works well. None the less I'm waiting for the update

**Comment by kal72** [comment]
I'm sorry I can not take updates, because I'm busy.
